### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by evenstephenr** [tannerlinsley/react-charts#103]
This is a meta-issue for ongoing roadmapping and prioritization work for [react-charts](https://github.com/tannerlinsley/react-charts)

#### Tasks
 
- [ ] label and give feedback on all open issues (match other react-* projects)
- [x] make a code sandbox example that includes react-charts and a working React sample app
- [x] Squash all of the bugs we know about
- [x] FINALLY solve the auto-rotating/auto-sizing scale issues ([issue link](https://github.com/tannerlinsley/react-charts/issues/70))
- [ ] Document the shiz out of everything
- [x] Give React Charts a new home at react-charts.tanstack.com similar to [React Query/Table](https://react-table.tanstack.com/)
- [ ] Assess core changes that need to be made to add more chart types
- [ ] Research / plan new chart types
- [ ] Drop the :microphone: 🌟 on a bunch of new charts and features
- [ ] Convert all non-drawing elements into their own html layers that are synced in position/size (this helps people customize all the things without having to know how to use svg)
- [ ] Design / add an annotations system that supports all types of annotations. Meta series, axis annotations, etc.
- [x] Add more voronoi options (the most needed one is a grid-based one, right now the best one we have is closest-to-point, but I'd like to have something better for scrubbing time-series charts

**Comment by tannerlinsley** [comment]
The new site it up

**Comment by sandcastle** [comment]
Please consider pie charts with v2, the only reason holding me back from using this is the lack of 🥧

**Comment by tannerlinsley** [comment]
Pie charts are still not on the roadmap. Sorry!

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
